name: go_app_driver
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#comparing dart objects
  equatable: ^2.0.5

  flutter_lints: ^2.0.0
   
  #state management
  flutter_bloc: ^8.1.2

  #make request to api
  internet_connection_checker: ^1.0.0+1
  #network
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  dio: ^5.3.3
  # Misc
  dartz: ^0.10.1

  #Database
  floor: any

  #Data class
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  cupertino_icons: ^1.0.2

  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  #service locator
  get_it: ^7.6.0
  injectable: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  #code generators
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  build_runner: ^2.4.6

  retrofit_generator: ^8.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
