name: go_app_driver
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#comparing dart objects
  equatable: ^2.0.5

  flutter_lints: ^2.0.0
   
  #state management
  flutter_bloc: ^8.1.2

  #make request to api
  internet_connection_checker: ^1.0.0+1
  #network
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  dio: ^5.3.3
  # Misc
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  #Database
  floor: any

  #Data class
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.2

  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  #service locator
  get_it: ^7.6.0
  injectable: ^2.3.2
  #map
  geolocator: ^10.1.0
  flutter_dotenv: ^5.1.0
  vietmap_flutter_gl: ^1.3.2
  vietmap_gl_platform_interface: ^0.1.2
  vietmap_flutter_navigation: ^1.4.7
  flutter_polyline_points: ^1.0.0
  #skeleton
  skeletons: ^0.0.3

  #lottie
  lottie: ^2.7.0

  flutter_easyloading: ^3.0.5
  
  flutter_rating_bar: ^4.0.1
  change_app_package_name: ^1.1.0
  # add this line to your dependencies
  toast: ^0.2.9
  talker: ^3.1.4
  intl: ^0.18.1

  stomp_dart_client: ^1.0.0

  flutter_spinkit: ^5.1.0

  fluttertoast: ^8.2.4

  polyline_codec: ^0.1.6

  flutter_phone_direct_caller: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #code generators
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  build_runner: ^2.4.6

  retrofit_generator: ^8.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
